export enum ROUTES {
  ADMIN = "/admin",
  DASHBOARD = "/dashboard",
  OVERVIEW = "overview",
  CATIGORIES = "catigories",
  Auth = "auth",
  LOGIN = "login",
  NOT_FOUND = "*",
  HOME = "",
  ABOUT ="about",
  CONTACT = "contact",
  CHECKOUT = "checkout",
  CART = "cart",
  PRODUCTS = "products",
  default= "",
}